services:
  mysql:
    image: mysql:8.0
    container_name: fn-ts
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql # Optional: initial SQL
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  # Optional: Adminer for DB management
  adminer:
    image: adminer:latest
    container_name: app_adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - mysql

volumes:
  mysql_data:
