# name: PR Check

# on:
#   pull_request:
#     types: [opened, synchronize, reopened]

# jobs:
#   check:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3

#     - name: Use Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '20.x'
#         cache: 'npm'

#     - name: Install dependencies
#       run: npm ci

#     - name: Run validation
#       run: npm run validate

#     - name: Comment PR
#       uses: actions/github-script@v6
#       if: failure()
#       with:
#         script: |
#           github.rest.issues.createComment({
#             issue_number: context.issue.number,
#             owner: context.repo.owner,
#             repo: context.repo.repo,
#             body: '❌ Validation failed! Please run `npm run validate` locally and fix any issues.'
#           })
